# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(519, 384)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 481, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.encrypt_key = QtWidgets.QPushButton(self.tab)
        self.encrypt_key.setGeometry(QtCore.QRect(140, 290, 151, 23))
        self.encrypt_key.setObjectName("encrypt_key")
        self.text_binary = QtWidgets.QLineEdit(self.tab)
        self.text_binary.setGeometry(QtCore.QRect(20, 140, 401, 21))
        self.text_binary.setText("")
        self.text_binary.setObjectName("text_binary")
        self.key_binary = QtWidgets.QLineEdit(self.tab)
        self.key_binary.setGeometry(QtCore.QRect(20, 190, 401, 21))
        self.key_binary.setText("")
        self.key_binary.setObjectName("key_binary")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(110, 220, 211, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.text_to_encrypt_box = QtWidgets.QLineEdit(self.tab)
        self.text_to_encrypt_box.setGeometry(QtCore.QRect(20, 30, 211, 21))
        self.text_to_encrypt_box.setText("")
        self.text_to_encrypt_box.setObjectName("text_to_encrypt_box")
        self.generated_key_box = QtWidgets.QLineEdit(self.tab)
        self.generated_key_box.setGeometry(QtCore.QRect(20, 80, 211, 21))
        self.generated_key_box.setText("")
        self.generated_key_box.setObjectName("generated_key_box")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(110, 170, 211, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(110, 120, 211, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.encrypted_message = QtWidgets.QLineEdit(self.tab)
        self.encrypted_message.setGeometry(QtCore.QRect(20, 240, 401, 21))
        self.encrypted_message.setText("")
        self.encrypted_message.setObjectName("encrypted_message")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 211, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.rule_box = QtWidgets.QLineEdit(self.tab)
        self.rule_box.setGeometry(QtCore.QRect(250, 30, 71, 21))
        self.rule_box.setText("")
        self.rule_box.setObjectName("rule_box")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(260, 10, 51, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.initial_state = QtWidgets.QLineEdit(self.tab)
        self.initial_state.setGeometry(QtCore.QRect(340, 30, 111, 21))
        self.initial_state.setText("")
        self.initial_state.setObjectName("initial_state")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(350, 10, 91, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.decrypted_message = QtWidgets.QLineEdit(self.tab_2)
        self.decrypted_message.setGeometry(QtCore.QRect(20, 170, 401, 21))
        self.decrypted_message.setText("")
        self.decrypted_message.setObjectName("decrypted_message")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(110, 50, 211, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.text_binary_encrypted = QtWidgets.QLineEdit(self.tab_2)
        self.text_binary_encrypted.setGeometry(QtCore.QRect(20, 70, 401, 21))
        self.text_binary_encrypted.setText("")
        self.text_binary_encrypted.setObjectName("text_binary_encrypted")
        self.decrypt_key = QtWidgets.QPushButton(self.tab_2)
        self.decrypt_key.setGeometry(QtCore.QRect(140, 220, 151, 23))
        self.decrypt_key.setObjectName("decrypt_key")
        self.key_binary_encrypted = QtWidgets.QLineEdit(self.tab_2)
        self.key_binary_encrypted.setGeometry(QtCore.QRect(20, 120, 401, 21))
        self.key_binary_encrypted.setText("")
        self.key_binary_encrypted.setObjectName("key_binary_encrypted")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(110, 150, 211, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(110, 100, 211, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.encrypt_key.setText(_translate("Dialog", "Encrypt"))
        self.label.setText(_translate("Dialog", "Insert text to encrypt"))
        self.label_5.setText(_translate("Dialog", "Binary encrypted text"))
        self.label_4.setText(_translate("Dialog", "Binary key"))
        self.label_3.setText(_translate("Dialog", "Binary text"))
        self.label_2.setText(_translate("Dialog", "Generated key"))
        self.label_6.setText(_translate("Dialog", "Reguła"))
        self.label_10.setText(_translate("Dialog", "Stan początkowy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Encrypt"))
        self.label_8.setText(_translate("Dialog", "Binary encrypted text"))
        self.decrypt_key.setText(_translate("Dialog", "Decrypt"))
        self.label_7.setText(_translate("Dialog", "Decrypted text"))
        self.label_9.setText(_translate("Dialog", "Binary key"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Decrypt"))

