# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_image.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(499, 616)
        self.encrypt_key = QtWidgets.QPushButton(Dialog)
        self.encrypt_key.setGeometry(QtCore.QRect(40, 390, 151, 23))
        self.encrypt_key.setObjectName("encrypt_key")
        self.radio_random_rules = QtWidgets.QRadioButton(Dialog)
        self.radio_random_rules.setGeometry(QtCore.QRect(320, 100, 161, 17))
        self.radio_random_rules.setObjectName("radio_random_rules")
        self.h_box = QtWidgets.QComboBox(Dialog)
        self.h_box.setGeometry(QtCore.QRect(210, 120, 69, 22))
        self.h_box.setObjectName("h_box")
        self.h_box.addItem("")
        self.h_box.addItem("")
        self.h_box.addItem("")
        self.h_box.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 91, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.eat_box = QtWidgets.QComboBox(Dialog)
        self.eat_box.setGeometry(QtCore.QRect(210, 150, 69, 22))
        self.eat_box.setObjectName("eat_box")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.decrypt_key = QtWidgets.QPushButton(Dialog)
        self.decrypt_key.setGeometry(QtCore.QRect(40, 420, 151, 23))
        self.decrypt_key.setObjectName("decrypt_key")
        self.cells_number = QtWidgets.QLineEdit(Dialog)
        self.cells_number.setGeometry(QtCore.QRect(140, 80, 141, 21))
        self.cells_number.setText("")
        self.cells_number.setObjectName("cells_number")
        self.radio_specified_rules = QtWidgets.QRadioButton(Dialog)
        self.radio_specified_rules.setGeometry(QtCore.QRect(320, 130, 151, 17))
        self.radio_specified_rules.setChecked(True)
        self.radio_specified_rules.setObjectName("radio_specified_rules")
        self.load_image = QtWidgets.QPushButton(Dialog)
        self.load_image.setGeometry(QtCore.QRect(320, 50, 151, 23))
        self.load_image.setObjectName("load_image")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(180, 120, 21, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 80, 91, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(40, 140, 171, 41))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.set_seed = QtWidgets.QPushButton(Dialog)
        self.set_seed.setGeometry(QtCore.QRect(330, 420, 121, 23))
        self.set_seed.setObjectName("set_seed")
        self.seed_amount_box = QtWidgets.QLineEdit(Dialog)
        self.seed_amount_box.setGeometry(QtCore.QRect(330, 390, 121, 21))
        self.seed_amount_box.setText("")
        self.seed_amount_box.setObjectName("seed_amount_box")
        self.key_binary = QtWidgets.QLineEdit(Dialog)
        self.key_binary.setGeometry(QtCore.QRect(50, 260, 401, 21))
        self.key_binary.setText("")
        self.key_binary.setObjectName("key_binary")
        self.text_binary = QtWidgets.QLineEdit(Dialog)
        self.text_binary.setGeometry(QtCore.QRect(50, 220, 401, 21))
        self.text_binary.setText("")
        self.text_binary.setObjectName("text_binary")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(140, 240, 211, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(140, 280, 211, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 200, 211, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.encrypted_message = QtWidgets.QLineEdit(Dialog)
        self.encrypted_message.setGeometry(QtCore.QRect(50, 300, 401, 21))
        self.encrypted_message.setText("")
        self.encrypted_message.setObjectName("encrypted_message")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(50, 50, 231, 21))
        self.frame.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.image_info = QtWidgets.QLabel(Dialog)
        self.image_info.setGeometry(QtCore.QRect(120, 50, 91, 20))
        self.image_info.setAlignment(QtCore.Qt.AlignCenter)
        self.image_info.setObjectName("image_info")
        self.output_name_box = QtWidgets.QLineEdit(Dialog)
        self.output_name_box.setGeometry(QtCore.QRect(40, 360, 151, 21))
        self.output_name_box.setText("")
        self.output_name_box.setObjectName("output_name_box")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 340, 211, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(40, 460, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 510, 211, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 480, 121, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.currently_iterate_box = QtWidgets.QLineEdit(Dialog)
        self.currently_iterate_box.setGeometry(QtCore.QRect(150, 480, 301, 21))
        self.currently_iterate_box.setText("")
        self.currently_iterate_box.setObjectName("currently_iterate_box")
        self.final_entropy_box = QtWidgets.QLineEdit(Dialog)
        self.final_entropy_box.setGeometry(QtCore.QRect(230, 510, 221, 21))
        self.final_entropy_box.setText("")
        self.final_entropy_box.setObjectName("final_entropy_box")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(330, 370, 121, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(30, 570, 421, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.progress_info = QtWidgets.QLabel(Dialog)
        self.progress_info.setGeometry(QtCore.QRect(110, 550, 261, 20))
        self.progress_info.setText("")
        self.progress_info.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_info.setObjectName("progress_info")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.encrypt_key.setText(_translate("Dialog", "Encrypt"))
        self.radio_random_rules.setText(_translate("Dialog", "Random rules (0-255)"))
        self.h_box.setItemText(0, _translate("Dialog", "4"))
        self.h_box.setItemText(1, _translate("Dialog", "2"))
        self.h_box.setItemText(2, _translate("Dialog", "3"))
        self.h_box.setItemText(3, _translate("Dialog", "5"))
        self.label.setText(_translate("Dialog", "File status"))
        self.eat_box.setItemText(0, _translate("Dialog", "1.0"))
        self.eat_box.setItemText(1, _translate("Dialog", "1.5"))
        self.eat_box.setItemText(2, _translate("Dialog", "1.9"))
        self.eat_box.setItemText(3, _translate("Dialog", "2.0"))
        self.eat_box.setItemText(4, _translate("Dialog", "2.5"))
        self.eat_box.setItemText(5, _translate("Dialog", "2.9"))
        self.eat_box.setItemText(6, _translate("Dialog", "3.0"))
        self.eat_box.setItemText(7, _translate("Dialog", "3.5"))
        self.eat_box.setItemText(8, _translate("Dialog", "3.9"))
        self.eat_box.setItemText(9, _translate("Dialog", "4.0"))
        self.decrypt_key.setText(_translate("Dialog", "Decrypt"))
        self.radio_specified_rules.setText(_translate("Dialog", "Rules 90, 105, 150, 165"))
        self.load_image.setText(_translate("Dialog", "Load File"))
        self.label_11.setText(_translate("Dialog", "h"))
        self.label_10.setText(_translate("Dialog", "Cells number"))
        self.label_12.setText(_translate("Dialog", "Entropy acceptance threshold"))
        self.set_seed.setText(_translate("Dialog", "Set seed"))
        self.label_4.setText(_translate("Dialog", "Binary key (first 100 digits)"))
        self.label_5.setText(_translate("Dialog", "Binary encrypted data (first 100 digits)"))
        self.label_3.setText(_translate("Dialog", "Binary data (first 100 digits)"))
        self.image_info.setText(_translate("Dialog", "file not loaded"))
        self.label_6.setText(_translate("Dialog", "output file name (with extension)"))
        self.label_7.setText(_translate("Dialog", "Entropy value for chosen key:"))
        self.label_8.setText(_translate("Dialog", "CA iterations: "))
        self.label_9.setText(_translate("Dialog", "seed value"))

