# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(519, 448)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 481, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.encrypt_key = QtWidgets.QPushButton(self.tab)
        self.encrypt_key.setGeometry(QtCore.QRect(160, 330, 151, 23))
        self.encrypt_key.setObjectName("encrypt_key")
        self.text_binary = QtWidgets.QLineEdit(self.tab)
        self.text_binary.setGeometry(QtCore.QRect(40, 190, 401, 21))
        self.text_binary.setText("")
        self.text_binary.setObjectName("text_binary")
        self.key_binary = QtWidgets.QLineEdit(self.tab)
        self.key_binary.setGeometry(QtCore.QRect(40, 240, 401, 21))
        self.key_binary.setText("")
        self.key_binary.setObjectName("key_binary")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(130, 270, 211, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.text_to_encrypt_box = QtWidgets.QLineEdit(self.tab)
        self.text_to_encrypt_box.setGeometry(QtCore.QRect(30, 30, 231, 21))
        self.text_to_encrypt_box.setText("")
        self.text_to_encrypt_box.setObjectName("text_to_encrypt_box")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(130, 220, 211, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(130, 170, 211, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.encrypted_message = QtWidgets.QLineEdit(self.tab)
        self.encrypted_message.setGeometry(QtCore.QRect(40, 290, 401, 21))
        self.encrypted_message.setText("")
        self.encrypted_message.setObjectName("encrypted_message")
        self.cells_number = QtWidgets.QLineEdit(self.tab)
        self.cells_number.setGeometry(QtCore.QRect(120, 60, 141, 21))
        self.cells_number.setText("")
        self.cells_number.setObjectName("cells_number")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 91, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.h_box = QtWidgets.QComboBox(self.tab)
        self.h_box.setGeometry(QtCore.QRect(190, 100, 69, 22))
        self.h_box.setObjectName("h_box")
        self.h_box.addItem("")
        self.h_box.addItem("")
        self.h_box.addItem("")
        self.h_box.addItem("")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(160, 100, 21, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 120, 171, 41))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.eat_box = QtWidgets.QComboBox(self.tab)
        self.eat_box.setGeometry(QtCore.QRect(190, 130, 69, 22))
        self.eat_box.setObjectName("eat_box")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.eat_box.addItem("")
        self.radio_random_rules = QtWidgets.QRadioButton(self.tab)
        self.radio_random_rules.setGeometry(QtCore.QRect(300, 50, 161, 17))
        self.radio_random_rules.setObjectName("radio_random_rules")
        self.radio_specified_rules = QtWidgets.QRadioButton(self.tab)
        self.radio_specified_rules.setGeometry(QtCore.QRect(300, 80, 151, 17))
        self.radio_specified_rules.setChecked(True)
        self.radio_specified_rules.setObjectName("radio_specified_rules")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.decrypted_message = QtWidgets.QLineEdit(self.tab_2)
        self.decrypted_message.setGeometry(QtCore.QRect(40, 170, 401, 21))
        self.decrypted_message.setText("")
        self.decrypted_message.setObjectName("decrypted_message")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(130, 50, 211, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.text_binary_encrypted = QtWidgets.QLineEdit(self.tab_2)
        self.text_binary_encrypted.setGeometry(QtCore.QRect(40, 70, 401, 21))
        self.text_binary_encrypted.setText("")
        self.text_binary_encrypted.setObjectName("text_binary_encrypted")
        self.decrypt_key = QtWidgets.QPushButton(self.tab_2)
        self.decrypt_key.setGeometry(QtCore.QRect(160, 220, 151, 23))
        self.decrypt_key.setObjectName("decrypt_key")
        self.key_binary_encrypted = QtWidgets.QLineEdit(self.tab_2)
        self.key_binary_encrypted.setGeometry(QtCore.QRect(40, 120, 401, 21))
        self.key_binary_encrypted.setText("")
        self.key_binary_encrypted.setObjectName("key_binary_encrypted")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(130, 150, 211, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(130, 100, 211, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.encrypt_key.setText(_translate("Dialog", "Encrypt"))
        self.label.setText(_translate("Dialog", "Insert text to encrypt"))
        self.label_5.setText(_translate("Dialog", "Binary encrypted text"))
        self.label_4.setText(_translate("Dialog", "Binary key"))
        self.label_3.setText(_translate("Dialog", "Binary text"))
        self.label_10.setText(_translate("Dialog", "Cells number"))
        self.h_box.setItemText(0, _translate("Dialog", "4"))
        self.h_box.setItemText(1, _translate("Dialog", "2"))
        self.h_box.setItemText(2, _translate("Dialog", "3"))
        self.h_box.setItemText(3, _translate("Dialog", "5"))
        self.label_11.setText(_translate("Dialog", "h"))
        self.label_12.setText(_translate("Dialog", "Entropy acceptance threshold"))
        self.eat_box.setItemText(0, _translate("Dialog", "1.0"))
        self.eat_box.setItemText(1, _translate("Dialog", "1.5"))
        self.eat_box.setItemText(2, _translate("Dialog", "1.9"))
        self.eat_box.setItemText(3, _translate("Dialog", "2.0"))
        self.eat_box.setItemText(4, _translate("Dialog", "2.5"))
        self.eat_box.setItemText(5, _translate("Dialog", "2.9"))
        self.eat_box.setItemText(6, _translate("Dialog", "3.0"))
        self.eat_box.setItemText(7, _translate("Dialog", "3.5"))
        self.eat_box.setItemText(8, _translate("Dialog", "3.9"))
        self.eat_box.setItemText(9, _translate("Dialog", "4.0"))
        self.radio_random_rules.setText(_translate("Dialog", "Random rules (0-255)"))
        self.radio_specified_rules.setText(_translate("Dialog", "Rules 90, 105, 150, 165"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Encrypt"))
        self.label_8.setText(_translate("Dialog", "Binary encrypted text"))
        self.decrypt_key.setText(_translate("Dialog", "Decrypt"))
        self.label_7.setText(_translate("Dialog", "Decrypted text"))
        self.label_9.setText(_translate("Dialog", "Binary key"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Decrypt"))

